export { MainPage } from "./main-page/MainPage";
export { CabinetPage } from './cabinet-page/CabinetPage'
export { CreateEventPage } from './create-event-page/CreateEventPage'
export { ContestResultsPage } from './contest-results-page/ContestResultsPage'
export { JuryContestPage } from './jury-contest-page/JuryContestPage'
export { OrganizerContestPage } from './organizer-contest-page/OrganizerContestPage'
export { OrganizerSignUpPage } from './organizer-sign-up-page/OrganizerSignUpPage'
export { OrganizerSignInPage } from './organizer-sign-in-page/OrganizerSignInPage'
export { JurySignInPage } from './jury-sign-in-page/JurySignInPage'